services:
  postgres:
    image: postgres:16.3-bullseye
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    volumes:
      - compute-marketplace-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  compute-marketplace-data: